{% set name = "arviz-base" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arviz_base-{{ version }}.tar.gz
  sha256: de88d36085361062221250dc37d12ad102544ac20de8d84e09326bfd7a081112

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - flit-core >=3.4,<4
    - pip
  run:
    - python
    - numpy >=2
    - xarray >=2024.11.0
    - typing_extensions >=3.10
    - lazy_loader >=0.4

test:
  imports:
    - arviz_base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arviz-devs/arviz-base
  summary: Base ArviZ features and converters.
  description: |
    Base ArviZ features, data converters, and shared utilities for the ArviZ
    ecosystem.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://arviz-base.readthedocs.io
  dev_url: https://github.com/arviz-devs/arviz-base


extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
